spring:
  application:
    name: l23-spring-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_data_example_db
    password: root
    username: root
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: /api

#custom:
#  datasource:
#    password: another-password
#    username: another-username
#    url: some-another-url
#custom.datasource.password=another-password
#custom.datasource.username=another-username
#custom.datasource.url=some-another-url