spring:
  application:
    name: spring-data-jpa
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    username: root
    url: jdbc:mysql://localhost:3306/spring_data_example_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
